-- CryptoHub BBS Database Setup
-- 运行地址: https://krtnkpvqxxfemgqluslr.supabase.co

-- 创建 users 表
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  avatar TEXT DEFAULT '',
  role TEXT DEFAULT 'user',
  wallet_address TEXT,
  bio TEXT,
  followers_count BIGINT DEFAULT 0,
  following_count BIGINT DEFAULT 0,
  total_profit DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建 topics 表
CREATE TABLE IF NOT EXISTS topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section TEXT NOT NULL,
  author_id BIGINT REFERENCES users(id),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  preview TEXT,
  tags TEXT[] DEFAULT '{}',
  is_hot BOOLEAN DEFAULT FALSE,
  is_new BOOLEAN DEFAULT FALSE,
  views_count BIGINT DEFAULT 0,
  likes_count BIGINT DEFAULT 0,
  comments_count BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建 comments 表
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id BIGINT REFERENCES topics(id) ON DELETE CASCADE,
  author_id BIGINT REFERENCES users(id),
  content TEXT NOT NULL,
  likes_count BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 插入示例用户
INSERT INTO users (username, avatar, role, bio, followers_count, total_profit) VALUES
('TraderZhang', 'T', 'vip', 'BTC 现货交易专家，专注趋势跟踪', 1234, 156.5),
('SolStrategy', 'S', 'expert', 'SOL 生态布道者，链上数据分析', 892, 89.2),
('ArbitrageKing', 'A', 'user', '套利策略研究者', 567, 24.5),
('DeFiHunter', 'D', 'user', 'DeFi 套利猎人', 432, 45.8);

-- 插入示例主题
INSERT INTO topics (section, author_id, title, content, preview, tags, is_hot, views_count, likes_count, comments_count) VALUES
('follow', 1, 'BTC 现货分批建仓策略，分享实盘信号', '目前行情处于相对低位，建议分批布局现货。我个人会在 95k-98k 区间逐步建仓，设置好止损在 90k。关键是要控制仓位，不要杠杆过大。支撑位 95k-98k 可以逐步买入，阻力位 102k-105k 可以考虑减仓。', '目前行情处于相对低位，建议分批布局现货，支撑位 95k-98k 可以逐步买入...', ARRAY['BTC', '现货', '建仓'], TRUE, 5432, 1200, 328),
('follow', 2, 'SOL 链上巨鲸地址异动，多单信号确认', '链上数据显示，某巨鲸地址近24小时持续增持 SOL。通过分析链上转移记录，发现多个大额地址正在悄悄建仓。这个信号值得我们关注。目标价位 180-200 USDT。', '监测到 SOL 链上某巨鲸地址近24小时持续增持，链上数据显示大单持续买入...', ARRAY['SOL', '链上数据'], FALSE, 3211, 567, 156),
('arbitrage', 3, 'BTC 期现套利机会分析 - CBOE vs Binance 价差', '当前 CBOE 期货价格比 Binance 现货高 2.3%，扣除资金成本后年化收益约 15-20%。操作策略：卖出 CBOE 期货，买入 Binance 现货，等待价差收敛。', '当前 CBOE 期货价格比 Binance 现货高 2.3%，考虑资金成本后年化收益约 15-20%...', ARRAY['BTC', '期现套利', '套利'], TRUE, 2345, 312, 89),
('arbitrage', 4, 'Curve / Aave 循环贷套利实盘记录', '利用 CRV 质押挖矿收益 + Aave 借贷利差进行循环操作。具体操作：存入 USDC 到 Aave 借出 USDT，存入 USDT 到 Curve 提供流动性获取 CRV 奖励。单日收益 0.15%，月化约 4.5%。', '利用 CRV 质押收益 + 借贷利差进行循环操作，单日收益 0.15%...', ARRAY['DeFi', '套利', 'CRV', 'Aave'], FALSE, 4567, 876, 234);

-- 创建索引优化查询性能
CREATE INDEX IF NOT EXISTS idx_topics_section ON topics(section);
CREATE INDEX IF NOT EXISTS idx_topics_author ON topics(author_id);
CREATE INDEX IF NOT EXISTS idx_topics_created ON topics(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_topics_hot ON topics(is_hot) WHERE is_hot = TRUE;

-- 验证查询
SELECT 'Users:' as table_name, COUNT(*) as count FROM users
UNION ALL
SELECT 'Topics:', COUNT(*) FROM topics
UNION ALL
SELECT 'Comments:', COUNT(*) FROM comments;
